# -*- coding: utf-8 -*-
"""streamlit app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYtwyWXZ8T7JGtxPa0EmhBNuhvqhjdKq
"""

!head -20 app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import joblib
# 
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder, StandardScaler
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# from sklearn.metrics import classification_report, confusion_matrix
# 
# from sklearn.linear_model import LogisticRegression
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.naive_bayes import GaussianNB
# 
# from sklearn.cluster import KMeans
# from scipy.cluster.hierarchy import linkage, dendrogram
# # Title
# st.title("📊 Telco Customer Churn Dashboard")
# # Load Dataset
# df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
# df.drop("customerID", axis=1, inplace=True)
# df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
# df.fillna(df["TotalCharges"].median(), inplace=True)
# # Encoding
# le = LabelEncoder()
# 
# for col in df.columns:
#     if df[col].dtype == "object":
#         df[col] = le.fit_transform(df[col])
# # Sidebar
# st.sidebar.title("Navigation")
# option = st.sidebar.radio(
#     "Go to:",
#     ["Dataset", "EDA", "Model Training", "Clustering", "Prediction"]
# )
# # Dataset Section
# if option == "Dataset":
#     st.subheader("Dataset Preview")
#     st.dataframe(df.head())
# 
#     st.write("Shape:", df.shape)
# # EDA Section
# elif option == "EDA":
#     st.subheader("Churn Distribution")
# 
#     fig1, ax1 = plt.subplots()
#     sns.countplot(x="Churn", data=df, ax=ax1)
#     st.pyplot(fig1)
# 
#     st.subheader("Correlation Heatmap")
# 
#     fig2, ax2 = plt.subplots(figsize=(10,6))
#     sns.heatmap(df.corr(), cmap="coolwarm", ax=ax2)
#     st.pyplot(fig2)
# 
# # Model Training
# elif option == "Model Training":
# 
#     X = df.drop("Churn", axis=1)
#     y = df["Churn"]
# 
#     scaler = StandardScaler()
#     X_scaled = scaler.fit_transform(X)
# 
#     X_train, X_test, y_train, y_test = train_test_split(
#         X_scaled, y, test_size=0.2, random_state=42
#     )
# 
#     models = {
#         "Logistic Regression": LogisticRegression(max_iter=1000),
#         "Decision Tree": DecisionTreeClassifier(),
#         "Random Forest": RandomForestClassifier(),
#         "KNN": KNeighborsClassifier(),
#         "Naive Bayes": GaussianNB()
#     }
# 
#     results = []
# 
#     st.subheader("Model Results")
# 
#     for name, model in models.items():
#         model.fit(X_train, y_train)
#         pred = model.predict(X_test)
# 
#         acc = accuracy_score(y_test, pred)
#         prec = precision_score(y_test, pred)
#         rec = recall_score(y_test, pred)
#         f1 = f1_score(y_test, pred)
# 
#         results.append([name, acc, prec, rec, f1])
# 
#         st.write("###", name)
#         st.text(classification_report(y_test, pred))
# 
#         fig, ax = plt.subplots()
#         sns.heatmap(confusion_matrix(y_test, pred), annot=True, fmt="d", ax=ax)
#         st.pyplot(fig)
# 
#     results_df = pd.DataFrame(results, columns=["Model","Accuracy","Precision","Recall","F1"])
# 
#     st.subheader("Comparison Table")
#     st.dataframe(results_df)
# 
#     fig3, ax3 = plt.subplots()
#     sns.barplot(x="Model", y="Accuracy", data=results_df, ax=ax3)
#     plt.xticks(rotation=20)
#     st.pyplot(fig3)
# 
#     # Save model
#     model = RandomForestClassifier()
#     model.fit(X_train, y_train)
#     joblib.dump(model, "model.pkl")
# 
#     st.success("Model trained and saved as model.pkl")
# # Clustering Section
# elif option == "Clustering":
# 
#     X = df.drop("Churn", axis=1)
#     scaler = StandardScaler()
#     X_scaled = scaler.fit_transform(X)
# 
#     kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
#     df["Cluster"] = kmeans.fit_predict(X_scaled)
# 
#     st.subheader("K-Means Clustering")
# 
#     fig4, ax4 = plt.subplots()
#     sns.scatterplot(
#         x=df["tenure"],
#         y=df["MonthlyCharges"],
#         hue=df["Cluster"],
#         ax=ax4
#     )
#     st.pyplot(fig4)
# 
#     st.subheader("Cluster Analysis")
#     st.dataframe(df.groupby("Cluster").mean())
# 
#     st.write("Business Insights:")
#     st.write("- Identify high churn customers")
#     st.write("- Target risky customers with offers")
#     st.write("- Use clusters for marketing")
# # Prediction Section
# elif option == "Prediction":
# import streamlit as st
# import numpy as np
# import joblib
# model = joblib.load("random_forest_model.pkl")
# st.title("Customer Churn Prediction")
# tenure = st.number_input("Tenure", 0)
# monthly = st.number_input("Monthly Charges", 0.0)
# if st.button("Predict"):
#     pred = model.predict([[tenure, monthly]])
#     st.write("Raw Prediction =", pred)
#     if pred[0] == 1:
#         st.error("Customer Will Churn")
#     else:
#         st.success("Customer Will Stay")
# st.write("App is running")