# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vu4BvTmAh5iZxS1oTBP3XHpSgpBeknMG
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler  # Sab se upar

# ... baqi ka code ...


import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import linkage, dendrogram

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)



df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

print(df.head())

print(df.shape)

print(df.columns)
# Data Cleaning
df.drop("customerID", axis=1, inplace=True)

df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)
df.fillna(df["TotalCharges"].median(), inplace=True)

# Encoding
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])
# EDA

plt.figure(figsize=(6,4))

sns.countplot(x="Churn", data=df)

plt.title("Customer Churn Distribution")

st.pyplot(plt)

plt.figure(figsize=(14,10))

sns.heatmap(
    df.corr(numeric_only=True),
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

st.pyplot(plt)

# Features and Target
X = df.drop(columns=['Churn']) # Churn aapka target column hoga
X = X.select_dtypes(include=['number'])
X = X.fillna(0)



# 2. Phir data tayyar karein
X = df.drop(columns=['Churn'], errors='ignore').select_dtypes(include=['number']).fillna(0)

# 3. Scaler ka object banayein (Yeh line fit_transform se PEHLE honi chahiye)
scaler = StandardScaler()

# 4. Ab data ko scale karein
X_scaled = scaler.fit_transform(X)
y = df["Churn"]
# Scaling

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# SUPERVISED LEARNING
models = {
    "Logistic Regression":
        LogisticRegression(max_iter=1000),

    "Decision Tree":
        DecisionTreeClassifier(),

    "Random Forest":
        RandomForestClassifier(),

    "KNN":
        KNeighborsClassifier(),

    "Naive Bayes":
        GaussianNB()
}
results = []
for name, model in models.items():

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

# Sahi Tareeqa:
accuracy = accuracy_score(y_test, pred)
    

precision = precision_score(
    y_test,
    pred,
    pos_label='Yes'  # Apni asli positive class ka naam yahan likhein
)

recall = recall_score(y_test, pred, average='macro')
f1 = f1_score(y_test, pred, average='macro')

results.append([
    name,
    accuracy,
    precision,
    recall,
    f1
    ])

print("\n====================")
print(name)
print("====================")

print(
    classification_report(
        y_test,
        pred
        )
    )

cm = confusion_matrix(
     y_test,
     pred
    )

plt.figure(figsize=(5,4))

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
    )

plt.title(
    f"Confusion Matrix - {name}"
    )

plt.show()
# Comparison Table
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1"
    ]
)
print(results_df)
# Accuracy Comparison Graph
plt.figure(figsize=(8,5))

sns.barplot(
    x="Model",
    y="Accuracy",
    data=results_df
)

plt.xticks(rotation=20)

plt.title(
    "Model Accuracy Comparison"
)

plt.show()
# Features and Target
X = df.drop("Churn", axis=1)

y = df["Churn"]
# Scaling
scaler = StandardScaler()
# Line 224 se theek PEHLE yeh lines add karein:
# 1. Target column (e.g., 'Churn') agar majood hai to drop karein
if 'Churn' in X.columns:
    X = X.drop(columns=['Churn'])

# 2. Sirf number wale columns select karein (Taake Text/String columns khatam ho jayein)
X = X.select_dtypes(include=['number'])

# 3. Agar koi missing value (khali cell) hai to usay 0 se bhar dein
X = X.fillna(0)

# Aapki Line 224 ab bilkul sahi chalegi:
X_scaled = scaler.fit_transform(X)
X_scaled = scaler.fit_transform(X)
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# UNSUPERVISED LEARNING
# K-Means Clustering
kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(
    X_scaled
)

df["Cluster"] = clusters
# Cluster Visualization
plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df["tenure"],
    y=df["MonthlyCharges"],
    hue=df["Cluster"]
)

plt.title(
    "K-Means Customer Segmentation"
)

plt.xlabel("Tenure")

plt.ylabel("Monthly Charges")

plt.show()
# Hierarchical Clustering

linked = linkage(
    X_scaled[:500],
    method="ward"
)

plt.figure(figsize=(12,6))

dendrogram(linked)

plt.title(
    "Hierarchical Clustering Dendrogram"
)

plt.show()

# Cluster Analysis

print(
    df.groupby("Cluster").mean(numeric_only=True)
)
# BUSINESS INSIGHTS
print("\nBusiness Insights")

print(
    "1. Identify high churn customers."
)

print(
    "2. Target risky customers with discounts."
)

print(
    "3. Use clusters for marketing campaigns."
)

print(
    "4. Retain customers with high monthly charges."
)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import joblib

# Sirf 2 features
X = df[["tenure", "MonthlyCharges"]]

y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

joblib.dump(rf, "random_forest_model.pkl")

print("Model Saved")
import os
print(os.listdir())
model = joblib.load("random_forest_model.pkl")
